### ISSUE TITLE
Use HOME path as default for cloned data instead of GEM_ROOT

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-data-importer#38]
The `{GEM_ROOT}` path may not be writable, for example, in the case in Tebako (read-only filesystem). We should use the home path as default.

_Originally posted by @ronaldtse in https://github.com/metanorma/bipm-data-importer/pull/37#discussion_r957944004_

**Comment by webdev778** [comment]
Fixed by #37
