### ISSUE TITLE
(URGENT) All CIPM recommendations have moved to a new set of pages

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-data-importer#49]
All CIPM recommendations are now at:
* https://www.bipm.org/en/committees/ci/cipm/recommendations

This is the cause of:
* https://github.com/metanorma/bipm-data-outcomes/issues/32
* https://github.com/metanorma/bipm-si-brochure/issues/228

This issue needs to be addressed by end of week (2024-12-13).

**Comment by hmdne** [comment]
CIPM resolutions and recommendations are not always linked anymore.

For instance this meeting has correct links:

https://www.bipm.org/fr/committees/ci/cipm/78-1989

But most don't.

**Comment by ronaldtse** [comment]
Not all CIPM Recommendations are shown on the website, and not all CIPM Recommendations provided are linked from/to the corresponding meeting page. 

However, that does not stop us from obtaining and linking the correct information. Thanks

**Comment by hmdne** [comment]
Meetings for which resolutions are missing from a currently producible dataset that were previously available:

- cctf/meetings-en/meeting-21.yml (en+fr)
- cipm (most, as mentioned by this issue)
- jcrb (most, if not all)
  - eg. this used to link correctly: https://www.bipm.org/fr/committees/jc/jcrb/9-2002

**Comment by hmdne** [comment]
@ronaldtse 

In my current state, the following documents have their resolutions emptied, compared to previous data:
- cctf/meetings-xx/meeting-21.yml (both languages)
- cipm/meetings-fr/meeting-93.yml (only FR, EN was empty previously)

I will produce a pull request briefly, as there is some untagged content that perhaps I can extract further. The rest is parsed now.
