### ISSUE TITLE
Add DOI information for CIPM and CGPM recommendations / decisions / outcomes

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-data-importer#52]
Each of these items are now assigned a DOI:

https://www.bipm.org/en/publications/si-brochure/annex-1/complete-list

e.g. 
https://www.bipm.org/en/committees/cg/cgpm/3-1901/resolution-2

**Comment by hmdne** [comment]
This has been already solved in:

https://github.com/metanorma/bipm-data-importer/pull/46/files#diff-64fff4388c30f62150a061571cd0f5d37a018b0ddeb28c56f8bedf2a86fd7e10R257

**Comment by hmdne** [comment]
As mentioned above, DOI numbers are extracted, so this issue can be closed.
